---
- name: add new admin  users    
  hosts: all
  connection: local
  tasks:
    - name: Add new admin  user 
      ios_user:
        configured_password: password_goes_here
        name: admin
        state: present
        privilege: 15
