---
- name: Issue show commands to find switches with ISE config
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Show auth sessions
      ios_command:
        commands:
          - show auth sessions | count mab|dot1x
          - show run | inc dot1x default group
      register: if_data

    - name: Sessions count
      debug:
        var: if_data['stdout_lines'][0]
