---
- name: Ping test to a group of external hosts 
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: Test reachability to external host
      cisco.ios.ios_ping:
        dest: 8.8.8.8
