
---
- name: Remove Radius Server 
  hosts: routers,switches
  gather_facts: false
  connection: local
  tasks:
    - name: remove radius server from config 
      ios_config:
          lines: no radius server test123
           
           
    

    - name: save running to startup when modified
      ios_config:
        save_when: modified
