---
- name: Issue show commands
  hosts: routers,switches
  gather_facts: true
  connection: local
  tasks:
    - name: Show logging host
      ios_command:
        commands:
          - show run | include logging
      register: if_data

    - name: Interfaces output
      debug:
        var: if_data['stdout_lines'][0]
