---
- name: show int status 
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Show int status include connected
      ios_command:
        commands: 
        - show int status | inc connected
      vars:
        ansible_command_timeout: 60
      register: if_data

    - name: Connected Ports 
      debug:
        var: if_data['stdout_lines'][0]
   
    - name: show int status | count  connected
      ios_command:
        commands: 
        - show int status | count  connected
      vars:
        ansible_command_timeout: 60
      register: if_data2
     
    - name: Number of connected ports
      debug:
        var: if_data2['stdout_lines'][0] 
      
      
    - name: Show mac address table  
      ios_command:
        commands: 
        - show mac address-table  | inc DYNAMIC 
        - show mac address-table  | count DYNAMIC  
      vars:
        ansible_command_timeout: 60
      register: if_data3

    - name: Mac table and count of macs
      debug:
        var: if_data3['stdout_lines'][0] 
        
    - name: Show cdp nei 
      ios_command:
        commands: 
        - show cdp nei | inc AP|ap'
      vars:
        ansible_command_timeout: 60
      register: if_data4

    - name: CDP Neitghbors
      debug:
        var: if_data4['stdout_lines'][0] 
      
    - name: Show ip int brie 
      ios_command:
        commands: 
        - show ip int brie | exc unassigned
      vars:
        ansible_command_timeout: 60
      register: if_data4

    - name: IP interfaces
      debug:
        var: if_data4['stdout_lines'][0] 
   
    - name: Show inventory 
      ios_command:
        commands: 
        - show inventory
      vars:
        ansible_command_timeout: 60
      register: if_data4

    - name: Device Inventory 
      debug:
        var: if_data4['stdout_lines'][0] 
        
    - name: Show log 
      ios_command:
        commands: 
        - show log | inc {{Mo}}  {{Date}}
      vars:
        ansible_command_timeout: 60
      register: if_data4

    - name: Log output for  {{Mo}}  {{Date}}
      debug:
        var: if_data4['stdout_lines'][0] 
