---
- name: Delete telnet from switch
  hosts: telnet_option
  gather_facts: no
  connection: local
  tasks:
    - name: Set ssh configuration
      ios_config:
        lines:
         - line vty 0 4
         - length 0
         - transport input ssh
         - line vty 5 15
         - transport input none
